#!/usr/bin/env bash
# hermesBOX — Phase 7: appliance hardening (idempotent). Run AS user `mailbox` on the box.
# Wires boot ordering across the whole stack, fixes the degraded set-maxn-power.service,
# and makes `systemctl is-system-running` report `running`. Mutating — run via the main
# agent, not the read-only provisioning agent.
# Spec: docs/PRD-v1.0.0.md §8 Phase 7 · docs/ROADMAP-v1.0.0.md Phase 7 · Linear UMB-386
#
# Service topology hardened here (see docs/RUNBOOK.md):
#   ollama.service        — embeddings only (nomic-embed-text), exists (Phase 1)
#   hermes-gateway.service— agent + WhatsApp adapter host; spawns gbrain MCP (stdio).
#                           Generated by `hermes gateway install --system` (Phase 2/5).
#   hermesbox-dashboard.service / hermesbox-kiosk.service — Phase 6 (may not exist yet).
# We add ordering via DROP-INS only (never edit hermes/vendor-generated units), so a
# `hermes gateway install` or JetPack update does not clobber the boot contract.
set -euo pipefail
. "${HOME}/.hermesbox_env.sh" 2>/dev/null || true

SYSD="/etc/systemd/system"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GATEWAY_UNIT="hermes-gateway.service"
KIOSK_UNIT="hermesbox-kiosk.service"
log(){ printf '\n\033[1;36m[phase7]\033[0m %s\n' "$*"; }
have_unit(){ systemctl list-unit-files "$1" >/dev/null 2>&1 && systemctl cat "$1" >/dev/null 2>&1; }

# Install a drop-in file ($1=src under provisioning/) for unit ($2) as conf name ($3).
install_dropin(){
  local src="$1" unit="$2" name="$3" dir="${SYSD}/${unit}.d"
  sudo install -d -m 0755 "$dir"
  sudo install -m 0644 "${HERE}/${src}" "${dir}/${name}"
  echo "  installed ${dir}/${name}"
}

# ---------------------------------------------------------------------------
log "1/6 — fix set-maxn-power.service (203/EXEC: nvpmodel is /usr/sbin not /usr/bin)"
# nvpmodel really lives at /usr/sbin/nvpmodel on this image; board is already MAXN_SUPER.
if [ -x /usr/sbin/nvpmodel ]; then
  install_dropin 70-set-maxn-power.conf set-maxn-power.service hermesbox.conf
elif command -v nvpmodel >/dev/null 2>&1; then
  # Defensive: if a future image moves nvpmodel again, point the drop-in at wherever it is.
  NVP="$(command -v nvpmodel)"
  sudo install -d -m 0755 "${SYSD}/set-maxn-power.service.d"
  printf '[Service]\nExecStart=\nExecStart=-%s -m 2\nSuccessExitStatus=0 1\n' "$NVP" \
    | sudo tee "${SYSD}/set-maxn-power.service.d/hermesbox.conf" >/dev/null
  echo "  installed drop-in pointing at ${NVP}"
else
  echo "  WARN: nvpmodel not found — masking set-maxn-power.service to clear degraded state"
  sudo systemctl mask set-maxn-power.service
fi

# ---------------------------------------------------------------------------
log "2/6 — ensure network-online.target is real (NetworkManager-wait-online)"
# The gateway Wants=network-online.target for cloud inference; on this box neither
# wait-online provider was enabled, so the target was a no-op. NetworkManager is active.
if systemctl is-active --quiet NetworkManager; then
  sudo systemctl enable NetworkManager-wait-online.service >/dev/null 2>&1 || true
  echo "  NetworkManager-wait-online enabled"
elif systemctl is-active --quiet systemd-networkd; then
  sudo systemctl enable systemd-networkd-wait-online.service >/dev/null 2>&1 || true
  echo "  systemd-networkd-wait-online enabled"
else
  echo "  WARN: no recognized network manager active — network-online.target may not settle"
fi

# ---------------------------------------------------------------------------
log "3/6 — hermes-gateway boot ordering (After ollama + tailscaled)"
if have_unit "$GATEWAY_UNIT"; then
  install_dropin 70-hermes-gateway-ordering.conf "$GATEWAY_UNIT" hermesbox-ordering.conf
  sudo systemctl enable "$GATEWAY_UNIT" >/dev/null 2>&1 || true
else
  echo "  SKIP: ${GATEWAY_UNIT} not installed yet."
  echo "        Install it first (Phase 2/5):"
  echo "          sudo hermes gateway install --system --run-as-user ${USER}"
  echo "        then re-run this script to layer the ordering drop-in."
fi

# ---------------------------------------------------------------------------
log "4/6 — kiosk boot ordering (After dashboard + gateway) — Phase 6 unit"
if have_unit "$KIOSK_UNIT"; then
  install_dropin 70-hermesbox-kiosk-ordering.conf "$KIOSK_UNIT" hermesbox-ordering.conf
else
  echo "  SKIP: ${KIOSK_UNIT} not present yet (Phase 6). Re-run after the kiosk unit lands."
fi

# ---------------------------------------------------------------------------
log "5/6 — reload + retry the previously-failed maxn unit"
sudo systemctl daemon-reload
sudo systemctl reset-failed set-maxn-power.service 2>/dev/null || true
sudo systemctl restart set-maxn-power.service 2>/dev/null || true

# ---------------------------------------------------------------------------
log "6/6 — boot-to-ready snapshot"
"${HERE}/verify-phase7.sh" || true

log "Phase 7 hardening applied. Validate a real reboot with: ${HERE}/reboot-resilience.sh"
echo "PHASE7_HARDENING_DONE"
